"""'What to look at' and 'what to ask next' hints after each chat turn.

Deterministic on purpose: hints are built from the tool results just returned
and from the curves the well actually has, never generated by the LLM, so they
cannot point at data that is not there.
"""

import math
from typing import Any, Dict, List, Optional

from backend.petrophysics import default_window, get_well_curves_summary, scan_reservoir_sweetspots

MAX_NEXT = 3
MAX_OBSERVE = 3


def _m(x: float) -> str:
    return f"{x:.0f}" if abs(x - round(x)) < 0.05 else f"{x:.1f}"


def _window(top: float, bottom: float) -> str:
    """Viewing windows read better in whole metres (widened, never narrowed)."""
    return f"from {math.floor(top)} to {math.ceil(bottom)} m"


def _between(top: float, bottom: float) -> str:
    return f"between {math.floor(top)} and {math.ceil(bottom)} m"


class _Guide:
    def __init__(self) -> None:
        self.observe: List[str] = []
        self.next: List[Dict[str, str]] = []

    def look(self, text: str) -> None:
        if text not in self.observe and len(self.observe) < MAX_OBSERVE:
            self.observe.append(text)

    def ask(self, prompt: str, why: str) -> None:
        if all(n["prompt"] != prompt for n in self.next) and len(self.next) < MAX_NEXT:
            self.next.append({"prompt": prompt, "why": why})

    def as_dict(self) -> Dict[str, Any]:
        return {"observe": self.observe, "next": self.next}


def _well_facts(well_id: str) -> Optional[Dict[str, Any]]:
    try:
        return get_well_curves_summary(well_id)
    except Exception:
        return None


def _starter_prompts(g: _Guide, well: str, facts: Dict[str, Any]) -> None:
    caps, win = facts["capabilities"], facts["default_window"]
    g.ask(f"Show the 1D log for {well} from {win['top']} to {win['bottom']} m",
          f"A 100 m window {win['basis']}.")
    if caps["net_pay"]:
        g.ask(f"Scan {well} for sweet spots", "Finds every interval that passes the clean / porous / hydrocarbon tests.")
    g.ask(f"What curves does {well} have?", "Lists each curve, its unit and depth coverage.")


def starter_guide(well_id: str) -> Dict[str, Any]:
    """Hints for a well nobody has asked about yet (e.g. right after upload)."""
    g = _Guide()
    facts = _well_facts(well_id)
    if not facts:
        return g.as_dict()
    caps = facts["capabilities"]
    missing = [name.replace("_", " ") for name in ("gamma_ray", "resistivity", "density", "neutron") if not caps[name]]
    g.look(f"Logged from {_m(facts['start_depth'])} to {_m(facts['stop_depth'])} m MD with "
           f"{facts['total_curves']} curves. Nothing is plotted until you ask.")
    if missing:
        g.look(f"No {', '.join(missing)} curve found, so some analyses (net pay, crossplots) may be unavailable.")
    _starter_prompts(g, facts["well_id"], facts)
    return g.as_dict()


def _zones_in(well: str, top: float, bottom: float) -> List[Dict[str, Any]]:
    try:
        zones = scan_reservoir_sweetspots(well).get("sweetspots", [])
    except Exception:
        return []
    return [z for z in zones if z["base_depth"] >= top and z["top_depth"] <= bottom]


def suggest_next(tool_calls: List[Dict[str, Any]], active_well: Optional[str] = None) -> Dict[str, Any]:
    """Build the guide from the most recent successful tool call(s)."""
    g = _Guide()
    ok_calls = [t for t in tool_calls if isinstance(t.get("result"), dict) and "error" not in t["result"]]

    if not ok_calls:
        well = active_well or "Well1"
        return starter_guide(well) if _well_facts(well) else g.as_dict()

    last = ok_calls[-1]
    name, args, res = last["name"], last.get("args", {}), last["result"]
    well = res.get("well_id") or args.get("well_id") or active_well or "Well1"
    facts = _well_facts(well)
    caps = facts["capabilities"] if facts else {}
    win = facts["default_window"] if facts else None

    if name == "plot_1d_well_log":
        top, bottom = float(res.get("top_depth", 0)), float(res.get("bottom_depth", 0))
        g.look("Track 1: gamma ray swinging left (low API) marks clean sand; swinging right marks shale.")
        zones = _zones_in(well, top, bottom)
        if zones:
            z = zones[0]
            g.look(f"The pay scan flags {_m(z['top_depth'])}–{_m(z['base_depth'])} m in this window: check that "
                   "deep resistivity (Track 2) is high there and density/neutron cross over (yellow fill, Track 3).")
            g.ask(f"Compute net pay for {well} between {_m(z['top_depth'])} and {_m(z['base_depth'])} m",
                  "Turns what you see into thickness, porosity and saturation numbers.")
        else:
            g.look("Track 2: in clean sand, high deep resistivity suggests hydrocarbons; low suggests water.")
            if caps.get("net_pay"):
                g.ask(f"Scan {well} for sweet spots", "No pay was flagged in this window; the scan checks the whole well.")
        qc = res.get("density_quality") or {}
        if qc.get("intervals_m"):
            first = qc["intervals_m"][0]
            g.look(f"Red bands on Track 3 ({qc['flagged_m']} m of this window, e.g. {_m(first[0])}–{_m(first[1])} m) "
                   "mark where the density correction says the density reading is unreliable; don't trust "
                   "crossover or density porosity there.")
        if caps.get("density") and caps.get("neutron"):
            g.ask(f"Crossplot density vs neutron for {well} {_between(top, bottom)}",
                  "Shows sand, shale and light-hydrocarbon (gas-like) points as separate clouds.")
        if caps.get("net_pay"):
            g.ask(f"Compute net pay for {well} {_between(top, bottom)}", "Quantifies the whole window.")

    elif name == "scan_reservoir_sweetspots":
        zones = res.get("sweetspots", [])
        if zones:
            z = zones[0]
            g.look(f"{res.get('total_sweetspots_found', len(zones))} zone(s), {res.get('total_pay_thickness_m', 0)} m "
                   f"of pay in total. Best: {_m(z['top_depth'])}–{_m(z['base_depth'])} m "
                   f"({z['thickness_m']} m, porosity {z['avg_porosity'] * 100:.0f}%, Sw {z['avg_sw'] * 100:.0f}%).")
            g.ask(f"Show the 1D log for {well} {_window(z['top_depth'] - 15, z['base_depth'] + 15)}",
                  "See the best zone by eye: low GR, high resistivity, yellow crossover.")
            g.ask(f"Compute net pay for {well} between {_m(z['top_depth'])} and {_m(z['base_depth'])} m",
                  "Cutoff sensitivity and pay averages for the best zone.")
            if len(zones) > 1:
                z2 = zones[1]
                g.ask(f"Show the 1D log for {well} {_window(z2['top_depth'] - 15, z2['base_depth'] + 15)}",
                      "Compare with the second-ranked zone.")
        else:
            g.look("No interval passed all three tests (Vsh ≤ 30%, porosity ≥ 10%, Sw ≤ 50%) for 1.5 m or more.")
            if win:
                g.ask(f"Show the 1D log for {well} from {win['top']} to {win['bottom']} m", "Look at the logs directly.")
            g.ask(f"Compute net pay for {well} between {_m(facts['start_depth']) if facts else 0} and "
                  f"{_m(facts['stop_depth']) if facts else 0} m with Vsh cutoff 0.4 and porosity cutoff 0.08",
                  "Looser cutoffs show whether anything is close to passing.")

    elif name in ("compute_net_pay", "generate_reservoir_composite_report"):
        top, bottom = float(args.get("top_depth", 0)), float(args.get("bottom_depth", 0))
        net, gross = res.get("net_pay_m", 0), res.get("gross_interval_m", res.get("gross_thickness_m", 0))
        g.look(f"{net} m of the {gross} m interval passes all three tests.")
        unc = res.get("net_pay_uncertainty")
        if unc and unc.get("p10_m", 0) - unc.get("p90_m", 0) > 0.2 * max(net, 1e-6):
            g.look(f"Pay ranges {unc['p90_m']}–{unc['p10_m']} m across the cutoff grid, so the cutoff choice matters here.")
        qc = res.get("density_quality") or {}
        if qc.get("pay_on_flagged_density_m"):
            g.look(f"{qc['pay_on_flagged_density_m']} m of this pay sits where the density reading is flagged unreliable "
                   "(large density correction), so its porosity there is less certain.")
        g.ask(f"Show the 1D log for {well} from {_m(top)} to {_m(bottom)} m", "Check the pay intervals by eye.")
        if caps.get("density") and caps.get("neutron"):
            g.ask(f"Crossplot density vs neutron for {well} between {_m(top)} and {_m(bottom)} m",
                  "Shows whether the pay has a gas-like signature (low density, low neutron); logs alone cannot confirm gas vs oil.")
        g.ask(f"Scan {well} for sweet spots", "See how this interval ranks against the rest of the well.")

    elif name in ("plot_2d_crossplot", "plot_crossplot_picket"):
        if name == "plot_2d_crossplot":
            g.look("Points near the yellow sandstone line are clean sand; points pushed right (high neutron) are shale-rich.")
            g.look("Points pulled up and left (low density, low neutron) are a gas-like signature: light hydrocarbon, possibly gas. Logs alone cannot tell gas from light oil.")
        else:
            g.look("Points to the right of the 100% water line have lower water saturation (more hydrocarbon).")
        top, bottom = args.get("top_depth"), args.get("bottom_depth")
        if top is not None and bottom is not None and caps.get("net_pay"):
            g.ask(f"Compute net pay for {well} between {_m(float(top))} and {_m(float(bottom))} m",
                  "Put numbers on what the crossplot shows.")
        if win:
            g.ask(f"Show the 1D log for {well} from {win['top']} to {win['bottom']} m", "Relate the clusters to depth.")

    elif name == "get_well_curves_summary" and facts:
        return starter_guide(well)

    elif name.startswith("plot_3d"):
        g.look("The XY path is illustrative; the colors along the hole are computed from the logs.")
        if win:
            g.ask(f"Show the 1D log for {well} from {win['top']} to {win['bottom']} m", "The logs behind the colors.")

    # Fill any remaining slots with safe starters for this well.
    if facts and len(g.next) < MAX_NEXT:
        _starter_prompts(g, facts["well_id"], facts)
    return g.as_dict()
